/* Microsoft University — service worker.
   GENERATED by tools/make-sw.py. Do not edit by hand; edit the script.

   Strategy
     navigations   network first, fall back to cache, then /offline.html
     static assets cache first, refreshed in the background
     /api/*        network only — counters and live feeds must never be stale
     cross-origin  passed straight through, never cached
*/
const VERSION = "9cef276cbffa";
const CACHE = "msftu-" + VERSION;
const OFFLINE = "/offline.html";

const PRECACHE = [
  "/about.html",
  "/contact.html",
  "/course-today.html",
  "/events.html",
  "/exams.html",
  "/index.html",
  "/offline.html",
  "/resources.html",
  "/status.html",
  "/terms.html",
  "/training.html",
  "/verify.html",
  "/exam/ab-100.html",
  "/exam/ab-210.html",
  "/exam/ab-250.html",
  "/exam/ab-400.html",
  "/exam/ab-410.html",
  "/exam/ab-620.html",
  "/exam/ab-650.html",
  "/exam/ab-730.html",
  "/exam/ab-731.html",
  "/exam/ab-900.html",
  "/exam/ai-900.html",
  "/exam/az-104.html",
  "/exam/az-140.html",
  "/exam/az-204.html",
  "/exam/az-305.html",
  "/exam/az-400.html",
  "/exam/az-500.html",
  "/exam/az-700.html",
  "/exam/az-800.html",
  "/exam/az-801.html",
  "/exam/az-900.html",
  "/exam/dp-300.html",
  "/exam/dp-420.html",
  "/exam/dp-600.html",
  "/exam/dp-700.html",
  "/exam/dp-900.html",
  "/exam/gh-100.html",
  "/exam/gh-200.html",
  "/exam/gh-300.html",
  "/exam/gh-500.html",
  "/exam/gh-900.html",
  "/exam/mb-230.html",
  "/exam/mb-240.html",
  "/exam/mb-280.html",
  "/exam/mb-310.html",
  "/exam/mb-330.html",
  "/exam/mb-500.html",
  "/exam/mb-800.html",
  "/exam/mb-820.html",
  "/exam/md-102.html",
  "/exam/ms-102.html",
  "/exam/ms-700.html",
  "/exam/ms-721.html",
  "/exam/pl-200.html",
  "/exam/pl-300.html",
  "/exam/pl-400.html",
  "/exam/pl-900.html",
  "/exam/sc-100.html",
  "/exam/sc-200.html",
  "/exam/sc-300.html",
  "/exam/sc-401.html",
  "/exam/sc-500.html",
  "/exam/sc-900.html",
  "/css/aero.css",
  "/css/style.css",
  "/js/achievements.js",
  "/js/certificate.js",
  "/js/counter.js",
  "/js/events.js",
  "/js/news.js",
  "/js/pwa.js",
  "/js/site.js",
  "/js/terminal.js",
  "/js/tourmap.js",
  "/js/vendor/d3.min.js",
  "/js/vendor/qrcode.min.js",
  "/assets/geo/world-110m.geo.json",
  "/assets/app/icon-192.png",
  "/assets/app/icon-512.png",
  "/assets/app/apple-touch-icon.png",
  "/manifest.webmanifest",
  "/offline.html",
];

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    /* addAll is all-or-nothing; one 404 would fail the whole install, so
       fetch individually and keep going. */
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(url, { cache: "reload" });
        if (res.ok) await cache.put(url, res);
      } catch (e) { /* offline at install time — runtime caching will catch it */ }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith("msftu-") && k !== CACHE)
                          .map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   /* let the network handle it */
  if (url.pathname.startsWith("/api/")) return;      /* always live */

  if (req.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        cache.put(req, fresh.clone());
        return fresh;
      } catch (e) {
        const cached = await caches.match(req, { ignoreSearch: true });
        return cached || (await caches.match(OFFLINE)) ||
               new Response("Offline", { status: 503, headers: { "Content-Type": "text/plain" } });
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(req);
    if (cached) {
      /* refresh in the background so the next load is current */
      event.waitUntil((async () => {
        try {
          const fresh = await fetch(req);
          if (fresh.ok) (await caches.open(CACHE)).put(req, fresh);
        } catch (e) {}
      })());
      return cached;
    }
    try {
      const fresh = await fetch(req);
      if (fresh.ok && fresh.type === "basic") (await caches.open(CACHE)).put(req, fresh.clone());
      return fresh;
    } catch (e) {
      return new Response("", { status: 504 });
    }
  })());
});
