# -*- coding: utf-8 -*-
"""
Exam data for the prep hub.

`url`, `title` and `study_guide` were read from Microsoft Learn (the exam
URLs resolve through learn.microsoft.com/credentials/certifications/...),
so links stay correct. `blurb`, `who` and `tip` are our own words — we do
not copy Microsoft's exam descriptions or their skills-measured lists;
those live behind the official links on every page.

`pa` = a free official practice assessment exists for this exam.
"""

FAMILIES = [
    ("ai", "AI &amp; Business Value", "AB and AI exams — Copilot, agents and the business case for AI."),
    ("azure", "Azure &amp; Infrastructure", "The AZ track, from cloud fundamentals to architect level."),
    ("data", "Data, Fabric &amp; Analytics", "The DP track — databases, Fabric and analytics."),
    ("github", "GitHub", "The GH track — GitHub itself, Actions, Copilot and Advanced Security."),
    ("dynamics", "Dynamics 365", "The MB track — functional consultant and developer paths."),
    ("m365", "Microsoft 365 &amp; Teams", "The MS and MD track — tenant, endpoints and Teams."),
    ("power", "Power Platform", "The PL track — from fundamentals to developer."),
    ("security", "Security", "The SC track — the fastest-growing corner of the catalog."),
]

EXAMS = {
"AB-100": dict(fam="ai", level="Advanced", title="Agentic AI Business Solutions Architect",
    url="https://learn.microsoft.com/credentials/certifications/exams/ab-100/",
    sg="https://aka.ms/AB100-StudyGuide", pa=False,
    blurb="The architect-level exam for designing agentic AI solutions across Copilot Studio, Foundry and the Dynamics 365 and Power Platform stack.",
    who="Solution architects who already hold an associate-level Dynamics 365, Power Platform or Azure AI certification — it has prerequisites, so check before you book."),
"AB-730": dict(fam="ai", level="Beginner", title="AI Business Professional",
    url="https://learn.microsoft.com/credentials/certifications/ai-business-professional/",
    sg="https://aka.ms/ab730-StudyGuide", pa=True,
    blurb="AI skills for people who work with the business rather than the platform: where AI creates value, and how to use it responsibly day to day.",
    who="Business professionals, consultants and managers who need fluency without going deep into the technology."),
"AB-731": dict(fam="ai", level="Intermediate", title="AI Transformation Leader",
    url="https://learn.microsoft.com/credentials/certifications/ai-transformation-leader/",
    sg="https://aka.ms/ab731-StudyGuide", pa=True,
    blurb="Leading an organisation through AI adoption — strategy, governance, change and measuring whether any of it actually worked.",
    who="Leaders and programme owners driving AI transformation, not the engineers implementing it."),
"AB-900": dict(fam="ai", level="Beginner", title="Copilot and Agent Administration Fundamentals",
    url="https://learn.microsoft.com/credentials/certifications/copilot-and-agent-administration-fundamentals/",
    sg="https://aka.ms/ab900-StudyGuide", pa=True,
    blurb="The fundamentals of administering Microsoft 365 Copilot and agents: rollout, permissions, governance and the guardrails around them.",
    who="Administrators taking their first structured look at running Copilot and agents in a tenant."),
"AI-900": dict(fam="ai", level="Beginner", title="Microsoft Azure AI Fundamentals",
    url="https://learn.microsoft.com/credentials/certifications/exams/ai-900/",
    sg="https://aka.ms/AI900-StudyGuide", pa=True,
    blurb="The entry point to AI on Azure — core machine learning concepts, the Azure AI services, generative AI and responsible AI.",
    who="Anyone starting out with AI on Azure. No coding or data-science background needed."),

"AZ-104": dict(fam="azure", level="Intermediate", title="Microsoft Azure Administrator",
    url="https://learn.microsoft.com/credentials/certifications/azure-administrator/",
    sg="https://aka.ms/AZ104-StudyGuide", pa=True,
    blurb="The workhorse Azure exam: identity, governance, storage, compute, virtual networking and monitoring — the things you touch every day.",
    who="Administrators with six months of hands-on Azure. The most common first role-based Azure certification."),
"AZ-140": dict(fam="azure", level="Intermediate", title="Configuring and Operating Microsoft Azure Virtual Desktop",
    url="https://learn.microsoft.com/credentials/certifications/azure-virtual-desktop-specialty/",
    sg="https://aka.ms/AZ140-StudyGuide", pa=True,
    blurb="Planning, deploying and operating Azure Virtual Desktop — host pools, images, FSLogix profiles, access and the performance tuning that follows.",
    who="Desktop and infrastructure specialists running virtual desktops on Azure."),
"AZ-204": dict(fam="azure", level="Intermediate", title="Developing Solutions for Microsoft Azure",
    url="https://learn.microsoft.com/credentials/certifications/azure-developer/",
    sg="https://aka.ms/AZ204-StudyGuide", pa=True,
    blurb="Building on Azure: compute options, storage, security, integration and the monitoring and troubleshooting that comes with shipping to production.",
    who="Developers with a year or two of professional development and real Azure SDK experience."),
"AZ-305": dict(fam="azure", level="Advanced", title="Designing Microsoft Azure Infrastructure Solutions",
    url="https://learn.microsoft.com/credentials/certifications/exams/az-305/",
    sg="https://aka.ms/AZ305-StudyGuide", pa=True,
    blurb="The architect exam. Designing identity, governance, data storage, business continuity and infrastructure — trade-offs rather than button-clicking.",
    who="Architects who already know Azure operations well. Case-study heavy; experience matters more than memorisation."),
"AZ-400": dict(fam="azure", level="Advanced", title="Designing and Implementing Microsoft DevOps Solutions",
    url="https://learn.microsoft.com/credentials/certifications/exams/az-400/",
    sg="https://aka.ms/AZ400-StudyGuide", pa=True,
    blurb="DevOps end to end: source control, CI/CD pipelines, infrastructure as code, secrets, dependencies and feedback loops.",
    who="Engineers who live in pipelines. Expect both Azure DevOps and GitHub across the exam."),
"AZ-500": dict(fam="azure", level="Intermediate", title="Microsoft Azure Security Technologies",
    url="https://learn.microsoft.com/credentials/certifications/azure-security-engineer/",
    sg="https://aka.ms/AZ500-StudyGuide", pa=True,
    blurb="Securing Azure: identity and access, platform protection, data and application security, and security operations.",
    who="Security engineers working in Azure. Pairs naturally with SC-300 on the identity side."),
"AZ-700": dict(fam="azure", level="Intermediate", title="Designing and Implementing Microsoft Azure Networking Solutions",
    url="https://learn.microsoft.com/credentials/certifications/azure-network-engineer-associate/",
    sg="https://aka.ms/az700-StudyGuide", pa=True,
    blurb="Azure networking in depth — hybrid connectivity, routing, load balancing, private access to services and network security.",
    who="Network engineers moving into Azure, and Azure admins who want the networking layer properly nailed down."),
"AZ-800": dict(fam="azure", level="Intermediate", title="Administering Windows Server Hybrid Core Infrastructure",
    url="https://learn.microsoft.com/credentials/certifications/exams/az-800/",
    sg="https://aka.ms/AZ800-StudyGuide", pa=True,
    blurb="Windows Server where most of it actually lives: hybrid. Identity, compute, network infrastructure and storage across on-premises and Azure.",
    who="Windows Server administrators. Half of a pair — AZ-801 completes the hybrid administrator certification."),
"AZ-801": dict(fam="azure", level="Advanced", title="Configuring Windows Server Hybrid Advanced Services",
    url="https://learn.microsoft.com/credentials/certifications/exams/az-801/",
    sg="https://aka.ms/AZ801-StudyGuide", pa=True,
    blurb="The advanced half of the hybrid server track: security, high availability, disaster recovery, migration and troubleshooting.",
    who="Experienced Windows Server administrators. Take AZ-800 first."),
"AZ-900": dict(fam="azure", level="Beginner", title="Microsoft Azure Fundamentals",
    url="https://learn.microsoft.com/credentials/certifications/azure-fundamentals/",
    sg="https://aka.ms/AZ900-StudyGuide", pa=True,
    blurb="Cloud concepts, Azure architecture and services, and how management and governance work — plus pricing and support.",
    who="Anyone, technical or not, who needs a credible foundation in Azure. The most-taken Microsoft exam for a reason."),

"DP-300": dict(fam="data", level="Intermediate", title="Administering Microsoft Azure SQL Solutions",
    url="https://learn.microsoft.com/credentials/certifications/azure-database-administrator-associate/",
    sg="https://aka.ms/dp300-StudyGuide", pa=True,
    blurb="Running SQL on Azure: planning and deploying, securing, monitoring, optimising performance and automating the routine work.",
    who="Database administrators bringing SQL Server skills onto the Azure platform."),
"DP-420": dict(fam="data", level="Advanced", title="Azure Cosmos DB Developer Specialty",
    url="https://learn.microsoft.com/credentials/certifications/azure-cosmos-db-developer-specialty/",
    sg="https://aka.ms/dp420-StudyGuide", pa=True,
    blurb="Designing and building cloud-native applications on Azure Cosmos DB — data modelling, partitioning, querying and tuning throughput.",
    who="Developers building on Cosmos DB. Genuinely specialised; partitioning design is where people come unstuck."),
"DP-600": dict(fam="data", level="Intermediate", title="Implementing Analytics Solutions Using Microsoft Fabric",
    url="https://learn.microsoft.com/credentials/certifications/fabric-analytics-engineer-associate/",
    sg="https://aka.ms/dp600-StudyGuide", pa=True,
    blurb="Designing and building analytics in Microsoft Fabric — preparing and modelling data, then delivering it so people can actually use it.",
    who="Analytics engineers and BI professionals. The natural step up from PL-300."),
"DP-700": dict(fam="data", level="Intermediate", title="Implementing Data Engineering Solutions Using Microsoft Fabric",
    url="https://learn.microsoft.com/credentials/certifications/fabric-data-engineer-associate/",
    sg="https://aka.ms/DP700-StudyGuide", pa=True,
    blurb="Data engineering in Fabric: ingesting and transforming at scale, managing the analytics lifecycle, and monitoring and optimising what you built.",
    who="Data engineers working in Fabric, comfortable with SQL, PySpark or KQL."),
"DP-900": dict(fam="data", level="Beginner", title="Microsoft Azure Data Fundamentals",
    url="https://learn.microsoft.com/credentials/certifications/azure-data-fundamentals/",
    sg="https://aka.ms/dp900-StudyGuide", pa=True,
    blurb="Core data concepts and how relational, non-relational and analytics workloads work on Azure.",
    who="Anyone starting in data. A sensible first step before DP-300, DP-600 or DP-700."),

"GH-100": dict(fam="github", level="Intermediate", title="GitHub Administration",
    url="https://learn.microsoft.com/credentials/certifications/github-administration/",
    sg="https://aka.ms/GH100-StudyGuide", pa=True,
    blurb="Administering GitHub at organisation and enterprise scale — authentication, permissions, policies, and keeping a large estate healthy.",
    who="Administrators responsible for a GitHub organisation or enterprise."),
"GH-200": dict(fam="github", level="Intermediate", title="GitHub Actions",
    url="https://learn.microsoft.com/credentials/certifications/github-actions/",
    sg="https://aka.ms/GH200-StudyGuide", pa=True,
    blurb="Automating with GitHub Actions: building workflows, managing secrets and runners, and packaging what you build so others can reuse it.",
    who="Developers and DevOps engineers automating their delivery pipeline in GitHub."),
"GH-300": dict(fam="github", level="Intermediate", title="GitHub Copilot",
    url="https://learn.microsoft.com/credentials/certifications/github-copilot/",
    sg="https://aka.ms/GH300-StudyGuide", pa=True,
    blurb="Using GitHub Copilot well — prompt and context craft, the features across plans, plus privacy, content exclusions and responsible use.",
    who="Developers and technology managers rolling Copilot out to a team."),
"GH-500": dict(fam="github", level="Intermediate", title="GitHub Advanced Security",
    url="https://learn.microsoft.com/credentials/certifications/github-advanced-security/",
    sg="https://aka.ms/GH500-StudyGuide", pa=True,
    blurb="Securing the software supply chain with code scanning, secret scanning and dependency review — configuring them and acting on what they find.",
    who="Security-minded engineers and AppSec teams working in GitHub."),
"GH-900": dict(fam="github", level="Beginner", title="GitHub Foundations",
    url="https://learn.microsoft.com/credentials/certifications/github-foundations/",
    sg="https://aka.ms/GH900-StudyGuide", pa=True,
    blurb="The fundamentals of GitHub: repositories, collaboration through issues and pull requests, and how the platform fits together.",
    who="Anyone new to GitHub. The right starting point before GH-100, GH-200, GH-300 or GH-500."),

"MB-230": dict(fam="dynamics", level="Intermediate", title="Microsoft Dynamics 365 Customer Service Functional Consultant",
    url="https://learn.microsoft.com/credentials/certifications/exams/mb-230/",
    sg="https://aka.ms/MB230-StudyGuide", pa=True,
    blurb="Configuring Dynamics 365 Customer Service — cases, queues, entitlements, SLAs, knowledge management and the analytics on top.",
    who="Functional consultants implementing customer service solutions."),
"MB-240": dict(fam="dynamics", level="Intermediate", title="Microsoft Dynamics 365 Field Service Functional Consultant",
    url="https://learn.microsoft.com/credentials/certifications/exams/mb-240/",
    sg="https://aka.ms/MB240-StudyGuide", pa=True,
    blurb="Field Service end to end: work orders, scheduling and dispatch, inventory, assets and the mobile experience technicians actually use.",
    who="Functional consultants delivering field service implementations."),
"MB-280": dict(fam="dynamics", level="Intermediate", title="Dynamics 365 Customer Experience Analyst",
    url="https://learn.microsoft.com/credentials/certifications/d365-customer-experience-analyst-associate/",
    sg="https://aka.ms/MB280-StudyGuide", pa=True,
    blurb="Configuring the customer experience apps — sales, customer insights and the journeys that connect marketing to selling.",
    who="Consultants and analysts working across Dynamics 365 Sales and Customer Insights."),
"MB-310": dict(fam="dynamics", level="Intermediate", title="Microsoft Dynamics 365 Finance Functional Consultant",
    url="https://learn.microsoft.com/credentials/certifications/d365-functional-consultant-financials/",
    sg="https://aka.ms/mb310-StudyGuide", pa=True,
    blurb="Implementing Dynamics 365 Finance: ledgers, receivables and payables, budgeting, fixed assets and financial close.",
    who="Functional consultants with a finance background."),
"MB-330": dict(fam="dynamics", level="Intermediate", title="Microsoft Dynamics 365 Supply Chain Management Functional Consultant",
    url="https://learn.microsoft.com/credentials/certifications/d365-functional-consultant-supply-chain-management/",
    sg="https://aka.ms/mb330-StudyGuide", pa=True,
    blurb="Supply chain in Dynamics 365 — products and inventory, procurement, sales, warehousing and manufacturing.",
    who="Functional consultants implementing supply chain and manufacturing processes."),
"MB-500": dict(fam="dynamics", level="Intermediate", title="Dynamics 365: Finance and Operations Apps Developer",
    url="https://learn.microsoft.com/credentials/certifications/d365-finance-and-operations-apps-developer-associate/",
    sg="https://aka.ms/mb500-StudyGuide", pa=True,
    blurb="Extending the finance and operations apps — X++ development, data models, integrations and the application lifecycle around them.",
    who="Developers customising Dynamics 365 Finance and Operations."),
"MB-800": dict(fam="dynamics", level="Intermediate", title="Microsoft Dynamics 365 Business Central Functional Consultant",
    url="https://learn.microsoft.com/credentials/certifications/d365-business-central-functional-consultant-associate/",
    sg="https://aka.ms/MB800-StudyGuide", pa=True,
    blurb="Setting up and configuring Business Central — company setup, financials, purchasing, sales and inventory for smaller organisations.",
    who="Functional consultants delivering Business Central to SMB customers."),
"MB-820": dict(fam="dynamics", level="Intermediate", title="Microsoft Dynamics 365 Business Central Developer",
    url="https://learn.microsoft.com/credentials/certifications/d365-business-central-developer-associate/",
    sg="https://aka.ms/mb820-StudyGuide", pa=True,
    blurb="Building extensions for Business Central in AL — data and interface objects, integrations, testing and deployment.",
    who="Developers extending Business Central. MB-800 knowledge helps a great deal."),

"MD-102": dict(fam="m365", level="Intermediate", title="Endpoint Administrator",
    url="https://learn.microsoft.com/credentials/certifications/modern-desktop/",
    sg="https://aka.ms/md102-StudyGuide", pa=True,
    blurb="Managing and securing endpoints with Intune — deployment, identity and compliance, applications, and protecting the device fleet.",
    who="Endpoint and desktop administrators. The Intune exam, in practice."),
"MS-102": dict(fam="m365", level="Intermediate", title="Microsoft 365 Administrator",
    url="https://learn.microsoft.com/credentials/certifications/exams/ms-102/",
    sg="https://aka.ms/MS102-StudyGuide", pa=True,
    blurb="Running a Microsoft 365 tenant: deployment, identity and access with Microsoft Entra, threat protection and compliance.",
    who="Microsoft 365 administrators. The backbone certification for the M365 platform."),
"MS-700": dict(fam="m365", level="Intermediate", title="Managing Microsoft Teams",
    url="https://learn.microsoft.com/credentials/certifications/m365-teams-administrator-associate/",
    sg="https://aka.ms/ms700-StudyGuide", pa=True,
    blurb="Planning and configuring Teams — governance and lifecycle, chat and collaboration, meetings and the settings that keep it manageable.",
    who="Teams administrators and M365 admins who own collaboration."),
"MS-721": dict(fam="m365", level="Advanced", title="Collaboration Communications Systems Engineer",
    url="https://learn.microsoft.com/credentials/certifications/m365-collaboration-communications-systems-engineer/",
    sg="https://aka.ms/MS721-StudyGuide", pa=True,
    blurb="Teams Phone, meetings and meeting rooms — voice routing, certified devices, and troubleshooting call quality when it goes wrong.",
    who="Engineers responsible for voice and meeting rooms. Telephony experience is a real advantage."),

"PL-200": dict(fam="power", level="Intermediate", title="Microsoft Power Platform Functional Consultant",
    url="https://learn.microsoft.com/credentials/certifications/exams/pl-200/",
    sg="https://aka.ms/PL200-StudyGuide", pa=True,
    blurb="Configuring Dataverse, building apps and automations, and delivering a working Power Platform solution end to end.",
    who="Functional consultants and makers who configure more than they code."),
"PL-300": dict(fam="power", level="Intermediate", title="Microsoft Power BI Data Analyst",
    url="https://learn.microsoft.com/credentials/certifications/data-analyst-associate/",
    sg="https://aka.ms/pl300-StudyGuide", pa=True,
    blurb="Preparing, modelling and visualising data in Power BI — including the DAX and the model design that separate a report from a good report.",
    who="Analysts working in Power BI. One of the most useful certifications on this list for everyday work."),
"PL-400": dict(fam="power", level="Intermediate", title="Microsoft Power Platform Developer",
    url="https://learn.microsoft.com/credentials/certifications/power-platform-developer-associate/",
    sg="https://aka.ms/PL400-StudyGuide", pa=True,
    blurb="Extending Power Platform with code — plug-ins, custom connectors, client scripting and integrations beyond what configuration reaches.",
    who="Developers working alongside functional consultants on Power Platform projects."),
"PL-900": dict(fam="power", level="Beginner", title="Microsoft Power Platform Fundamentals",
    url="https://learn.microsoft.com/credentials/certifications/power-platform-fundamentals/",
    sg="https://aka.ms/PL900-StudyGuide", pa=True,
    blurb="What Power Platform is and what each part does — Power Apps, Power Automate, Power BI, Power Pages and Copilot Studio.",
    who="Anyone starting with Power Platform, including business users who will build their first app."),

"SC-100": dict(fam="security", level="Advanced", title="Microsoft Cybersecurity Architect",
    url="https://learn.microsoft.com/credentials/certifications/exams/sc-100/",
    sg="https://aka.ms/SC100-StudyGuide", pa=True,
    blurb="Designing a Zero Trust security strategy — architecture across identity, data, applications and infrastructure, and the governance around it.",
    who="Security architects. Expect one of SC-200, SC-300, AZ-500 or MS-102 behind you; this exam assumes that ground is covered."),
"SC-200": dict(fam="security", level="Intermediate", title="Microsoft Security Operations Analyst",
    url="https://learn.microsoft.com/credentials/certifications/security-operations-analyst/",
    sg="https://aka.ms/SC200-StudyGuide", pa=True,
    blurb="Threat detection and response with Defender XDR and Microsoft Sentinel — mitigating threats and hunting for what the alerts missed.",
    who="SOC analysts and security engineers. KQL is worth practising before you sit it."),
"SC-300": dict(fam="security", level="Intermediate", title="Microsoft Identity and Access Administrator",
    url="https://learn.microsoft.com/credentials/certifications/identity-and-access-administrator/",
    sg="https://aka.ms/sc300-StudyGuide", pa=True,
    blurb="Microsoft Entra in depth — identity lifecycle, authentication and conditional access, application access and identity governance.",
    who="Identity administrators. Identity is the control plane, which makes this one of the highest-leverage certifications here."),
"SC-401": dict(fam="security", level="Intermediate", title="Information Security Administrator",
    url="https://learn.microsoft.com/credentials/certifications/information-security-administrator/",
    sg="https://aka.ms/SC401-StudyGuide", pa=True,
    blurb="Protecting data with Microsoft Purview — information protection, data loss prevention, insider risk and retention.",
    who="Administrators who own data protection and compliance. The successor to the old SC-400."),
"SC-500": dict(fam="security", level="Intermediate", title="Implementing End-to-End Security Controls for Cloud and AI Workloads",
    url="https://learn.microsoft.com/credentials/certifications/cloud-and-ai-security-engineer-associate/",
    sg="https://aka.ms/SC500-StudyGuide", pa=False,
    blurb="Security across the whole estate rather than one product: identity and governance, storage, databases and networking, compute, and the platforms AI workloads actually run on.",
    who="Security engineers working across Azure and Microsoft 365 who now have AI workloads to protect as well. Earns the Cloud and AI Security Engineer Associate certification."),
"SC-900": dict(fam="security", level="Beginner", title="Microsoft Security, Compliance, and Identity Fundamentals",
    url="https://learn.microsoft.com/credentials/certifications/security-compliance-and-identity-fundamentals/",
    sg="https://aka.ms/sc900-StudyGuide", pa=True,
    blurb="The vocabulary and the map: security and compliance concepts, and what each Microsoft security, identity and compliance capability is for.",
    who="Anyone before starting the SC track — and business stakeholders who need to follow the conversation."),
}
