# -*- coding: utf-8 -*-
"""
App icons for the installable web app.

Deliberately an ORIGINAL mark — an "MU" monogram on the site's own blue —
rather than the four-square symbol used in the site header. A home-screen
icon is the one place the app stands alone with no disclaimer next to it,
so it should be unmistakably ours and not read as another company's logo.

Outputs into assets/app/:
    icon-192.png            standard
    icon-512.png            standard
    icon-192-maskable.png   content inside the 80% safe zone
    icon-512-maskable.png   content inside the 80% safe zone
    apple-touch-icon.png    180px, opaque (iOS rounds it itself)

Run:  python3 tools/make-app-icons.py
"""

import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "assets", "app")

BLUE_TOP = (0, 120, 212)     # #0078d4
BLUE_BOT = (0, 61, 107)      # #003d6b  (site --blue-darker)
WHITE = (255, 255, 255)

FONTS = [
    "/usr/share/fonts/truetype/google-fonts/Poppins-SemiBold.ttf",
    "/usr/share/fonts/truetype/lato/Lato-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
]


def font(size):
    for p in FONTS:
        if os.path.exists(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def gradient(size):
    """Vertical blue gradient, drawn row by row."""
    img = Image.new("RGB", (size, size))
    d = ImageDraw.Draw(img)
    for y in range(size):
        t = y / max(1, size - 1)
        d.line(
            [(0, y), (size, y)],
            fill=tuple(int(BLUE_TOP[i] + (BLUE_BOT[i] - BLUE_TOP[i]) * t) for i in range(3)),
        )
    return img


def draw_mark(img, scale):
    """MU monogram plus an underline rule, centred. `scale` is the fraction of
    the canvas the mark may occupy (smaller for maskable icons)."""
    size = img.size[0]
    d = ImageDraw.Draw(img)

    f = font(int(size * 0.34 * scale))
    text = "MU"
    box = d.textbbox((0, 0), text, font=f)
    w, h = box[2] - box[0], box[3] - box[1]
    x = (size - w) / 2 - box[0]
    y = (size - h) / 2 - box[1] - size * 0.045 * scale
    d.text((x, y), text, font=f, fill=WHITE)

    # underline: echoes the section rules on the site
    rule_w = w * 0.92
    rule_h = max(2, int(size * 0.022 * scale))
    rx = (size - rule_w) / 2
    ry = y + box[3] + size * 0.055 * scale
    d.rounded_rectangle([rx, ry, rx + rule_w, ry + rule_h],
                        radius=rule_h / 2, fill=(255, 255, 255, 255))
    return img


def build(size, maskable=False):
    img = gradient(size)
    draw_mark(img, 0.78 if maskable else 1.0)
    return img


def main():
    os.makedirs(OUT, exist_ok=True)
    jobs = [
        ("icon-192.png", 192, False),
        ("icon-512.png", 512, False),
        ("icon-192-maskable.png", 192, True),
        ("icon-512-maskable.png", 512, True),
        ("apple-touch-icon.png", 180, False),
    ]
    for name, size, mask in jobs:
        build(size, mask).save(os.path.join(OUT, name), "PNG", optimize=True)
        print("  wrote", name, "%dx%d" % (size, size))

    with open(os.path.join(OUT, "README.txt"), "w", encoding="utf-8") as fh:
        fh.write(
            "Home-screen icons for the installable web app.\n"
            "Generated by tools/make-app-icons.py — edit that, not these files.\n\n"
            "An original MU monogram, not the site header's four-square symbol:\n"
            "the icon sits alone on a home screen with no context around it, so\n"
            "it should read as ours.\n"
        )
    print("  wrote README.txt")


if __name__ == "__main__":
    main()
