# -*- coding: utf-8 -*-
"""
Builds sw.js — the service worker that makes the site installable and the
exam prep hub usable with no signal.

The precache list is generated rather than hand-written so it cannot drift
when exam pages are added. The cache version is a hash of the file contents,
so a deploy that changes anything automatically invalidates the old cache.

HIDDEN PAGES ARE EXCLUDED ON PURPOSE. sw.js is served publicly, so anything
named in it is discoverable by reading it. toolbox.html and visitors.html
must never appear here.

Run:  python3 tools/make-sw.py
"""

import hashlib
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))

# Never precache these, never name them in a public file.
# toolbox.js is the private link vault that toolbox.html reads — listing it
# here would point straight at it.
HIDDEN = {"toolbox.html", "visitors.html", "toolbox.js"}

# Not worth the bytes offline, or meaningless without the network.
SKIP_ROOT = {"404.html"}


def rel(path):
    return "/" + os.path.relpath(path, ROOT).replace(os.sep, "/")


def collect():
    files = []

    for name in sorted(os.listdir(ROOT)):
        if name.endswith(".html") and name not in HIDDEN and name not in SKIP_ROOT:
            files.append("/" + name)

    exam_dir = os.path.join(ROOT, "exam")
    if os.path.isdir(exam_dir):
        for name in sorted(os.listdir(exam_dir)):
            if name.endswith(".html"):
                files.append("/exam/" + name)

    for sub in ("css", "js", "js/vendor"):
        d = os.path.join(ROOT, *sub.split("/"))
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if name.endswith((".css", ".js")) and name not in HIDDEN:
                files.append("/" + sub + "/" + name)

    for extra in ("/assets/geo/world-110m.geo.json",
                  "/assets/app/icon-192.png",
                  "/assets/app/icon-512.png",
                  "/assets/app/apple-touch-icon.png",
                  "/manifest.webmanifest",
                  "/offline.html"):
        if os.path.exists(os.path.join(ROOT, extra.lstrip("/"))):
            files.append(extra)

    return files


def version(files):
    h = hashlib.sha256()
    for f in sorted(files):
        p = os.path.join(ROOT, f.lstrip("/"))
        h.update(f.encode("utf-8"))
        if os.path.exists(p):
            with open(p, "rb") as fh:
                h.update(fh.read())
    return h.hexdigest()[:12]


TEMPLATE = '''/* Microsoft University — service worker.
   GENERATED by tools/make-sw.py. Do not edit by hand; edit the script.

   Strategy
     navigations   network first, fall back to cache, then /offline.html
     static assets cache first, refreshed in the background
     /api/*        network only — counters and live feeds must never be stale
     cross-origin  passed straight through, never cached
*/
const VERSION = "%(version)s";
const CACHE = "msftu-" + VERSION;
const OFFLINE = "/offline.html";

const PRECACHE = [
%(files)s
];

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    /* addAll is all-or-nothing; one 404 would fail the whole install, so
       fetch individually and keep going. */
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(url, { cache: "reload" });
        if (res.ok) await cache.put(url, res);
      } catch (e) { /* offline at install time — runtime caching will catch it */ }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith("msftu-") && k !== CACHE)
                          .map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   /* let the network handle it */
  if (url.pathname.startsWith("/api/")) return;      /* always live */

  if (req.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        cache.put(req, fresh.clone());
        return fresh;
      } catch (e) {
        const cached = await caches.match(req, { ignoreSearch: true });
        return cached || (await caches.match(OFFLINE)) ||
               new Response("Offline", { status: 503, headers: { "Content-Type": "text/plain" } });
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(req);
    if (cached) {
      /* refresh in the background so the next load is current */
      event.waitUntil((async () => {
        try {
          const fresh = await fetch(req);
          if (fresh.ok) (await caches.open(CACHE)).put(req, fresh);
        } catch (e) {}
      })());
      return cached;
    }
    try {
      const fresh = await fetch(req);
      if (fresh.ok && fresh.type === "basic") (await caches.open(CACHE)).put(req, fresh.clone());
      return fresh;
    } catch (e) {
      return new Response("", { status: 504 });
    }
  })());
});
'''


def main():
    files = collect()
    body = "\n".join('  "%s",' % f for f in files)
    out = TEMPLATE % {"version": version(files), "files": body}
    with open(os.path.join(ROOT, "sw.js"), "w", encoding="utf-8") as fh:
        fh.write(out)

    leaked = [f for f in files if os.path.basename(f) in HIDDEN]
    print("  wrote sw.js — %d files precached, version %s" % (len(files), version(files)))
    print("  hidden pages leaked into sw.js:", leaked or "none")


if __name__ == "__main__":
    main()
